# Generated by Django 3.0.7 on 2020-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='displayContent',
            field=models.CharField(default=0, max_length=220),
            preserve_default=False,
        ),
    ]
