# Generated by Django 3.0.7 on 2020-08-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_displaycontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='displayContent',
            field=models.TextField(max_length=220),
        ),
    ]
